language: java
sudo: false
install: true
before_install:
  - pwd
  - cd Rom-tools
install:
  - mvn clean install -DskipTests
addons:
  sonarcloud:
    organization: "rsl1122-github"
    token:
      secure: "Sa/ndH2vlX60c86CDsNsKxfncZQY02qirTdIPVtt2ur0tXXLEnP7Pzc0mKnc11dn9Xv+Rwdbf4saf/QB5PMCf+PUgk3ntpLSYnRf/EJawt1294ERe0qEXn94E126NkS9lejwFDqsjG2j9TL1d7l71bCfH0lTeyNuGOBt+7dEEMZL6NIvJHTC8GffEsP4zo72DgvkHjfzgcUlDnuzFe/mT36SoRkzN936IchjogmjFS+hSyDkaB9EpmM33VArEKKUf+5+1yaEEIHhAmNmLFbjlAiwn88cwmpsbw5CI8BEpZZq1EtIiGHdM3KB1ebKUpG09eclDatg+xei+r0zhB6F3IgF/2nV2r5b+9mKNwHAzwwYRfMe71JqwoD8Ldo40HAX4ceiTNx8Un+CA3KRirMRBZpcO6UcPYigq3TIuNn9ZerLyWKO4c2DVrJ+xmNs4jPLYilzBo03ej1Yt6iSeAZuPao81tq16yGL5EpEiOdMSSM9LwLkAw9b0mqfjkJpkHAPao8rfho+sRyBA7gyQWRK1J/gLBYkrmo9l6ObIaH9h0CezhqmAJGZjWDutfD+ma8TSshNUul20mDKK926FRf70ktO+keYPEILNzxaf3ZgLQsArZ7SPJw2VVgh0ywK98ZXGKQ/yZPtzpB1kYLHvgGY5B3QtV0GJoUnrSqUnJMvgFc="
jdk:
  - oraclejdk8
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
  - mvn checkstyle:checkstyle
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
